// Initialize Supabase Keysconst 
supabaseUrl = 'https://zlzwwhepyoeeaflpgrwp.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsend3aGVweW9lZWFmbHBncndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNTkxNjksImV4cCI6MjA4OTgzNTE2OX0.QCgn4YPDrKUUfsbepvpsLbJ6UR5NExCgxSeJX54Hbz0';